# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1a0d7a302e6a8e38561d109e396c1cf90446d2e0eb57eef95eae12bedd0850fe97d6b6b4fc4004f77bb4a7ed1977986dd5ad39f98cb5648d2ae9b27aa9ed576f

test:
  secret_key_base: 4008b9ef41239f28dfb78ca590dbbf764eb2dfa4cc22db367eaace8fb6745fe8b87428098ea9b336ace2c5b33a087563456e7187aeab4a16a863931629e9107b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
